# Generated by Django 4.2.23 on 2025-08-26 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_post_excerpt"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
